// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pirmessage.proto
#ifndef GRPC_pirmessage_2eproto__INCLUDED
#define GRPC_pirmessage_2eproto__INCLUDED

#include "pirmessage.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace pir_message {

class PIRService final {
 public:
  static constexpr char const* service_full_name() {
    return "pir_message.PIRService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::pir_message::DBInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::DBInfo>> AsyncGetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::DBInfo>>(AsyncGetDBInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::DBInfo>> PrepareAsyncGetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::DBInfo>>(PrepareAsyncGetDBInfoRaw(context, request, cq));
    }
    virtual ::grpc::Status GetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::pir_message::ResponseData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::ResponseData>> AsyncGetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::ResponseData>>(AsyncGetPIRRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::ResponseData>> PrepareAsyncGetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::ResponseData>>(PrepareAsyncGetPIRRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest* request, ::pir_message::DBInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest* request, ::pir_message::DBInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData* request, ::pir_message::ResponseData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData* request, ::pir_message::ResponseData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::DBInfo>* AsyncGetDBInfoRaw(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::DBInfo>* PrepareAsyncGetDBInfoRaw(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::ResponseData>* AsyncGetPIRRaw(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pir_message::ResponseData>* PrepareAsyncGetPIRRaw(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::pir_message::DBInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::DBInfo>> AsyncGetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::DBInfo>>(AsyncGetDBInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::DBInfo>> PrepareAsyncGetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::DBInfo>>(PrepareAsyncGetDBInfoRaw(context, request, cq));
    }
    ::grpc::Status GetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::pir_message::ResponseData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::ResponseData>> AsyncGetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::ResponseData>>(AsyncGetPIRRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::ResponseData>> PrepareAsyncGetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pir_message::ResponseData>>(PrepareAsyncGetPIRRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest* request, ::pir_message::DBInfo* response, std::function<void(::grpc::Status)>) override;
      void GetDBInfo(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest* request, ::pir_message::DBInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData* request, ::pir_message::ResponseData* response, std::function<void(::grpc::Status)>) override;
      void GetPIR(::grpc::ClientContext* context, const ::pir_message::RequestData* request, ::pir_message::ResponseData* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pir_message::DBInfo>* AsyncGetDBInfoRaw(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pir_message::DBInfo>* PrepareAsyncGetDBInfoRaw(::grpc::ClientContext* context, const ::pir_message::DBInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pir_message::ResponseData>* AsyncGetPIRRaw(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pir_message::ResponseData>* PrepareAsyncGetPIRRaw(::grpc::ClientContext* context, const ::pir_message::RequestData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetDBInfo_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPIR_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetDBInfo(::grpc::ServerContext* context, const ::pir_message::DBInfoRequest* request, ::pir_message::DBInfo* response);
    virtual ::grpc::Status GetPIR(::grpc::ServerContext* context, const ::pir_message::RequestData* request, ::pir_message::ResponseData* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDBInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDBInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetDBInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDBInfo(::grpc::ServerContext* /*context*/, const ::pir_message::DBInfoRequest* /*request*/, ::pir_message::DBInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDBInfo(::grpc::ServerContext* context, ::pir_message::DBInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::pir_message::DBInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPIR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPIR() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetPIR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPIR(::grpc::ServerContext* /*context*/, const ::pir_message::RequestData* /*request*/, ::pir_message::ResponseData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPIR(::grpc::ServerContext* context, ::pir_message::RequestData* request, ::grpc::ServerAsyncResponseWriter< ::pir_message::ResponseData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetDBInfo<WithAsyncMethod_GetPIR<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetDBInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDBInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pir_message::DBInfoRequest, ::pir_message::DBInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pir_message::DBInfoRequest* request, ::pir_message::DBInfo* response) { return this->GetDBInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetDBInfo(
        ::grpc::MessageAllocator< ::pir_message::DBInfoRequest, ::pir_message::DBInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pir_message::DBInfoRequest, ::pir_message::DBInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDBInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDBInfo(::grpc::ServerContext* /*context*/, const ::pir_message::DBInfoRequest* /*request*/, ::pir_message::DBInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDBInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::pir_message::DBInfoRequest* /*request*/, ::pir_message::DBInfo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetPIR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPIR() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::pir_message::RequestData, ::pir_message::ResponseData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pir_message::RequestData* request, ::pir_message::ResponseData* response) { return this->GetPIR(context, request, response); }));}
    void SetMessageAllocatorFor_GetPIR(
        ::grpc::MessageAllocator< ::pir_message::RequestData, ::pir_message::ResponseData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pir_message::RequestData, ::pir_message::ResponseData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPIR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPIR(::grpc::ServerContext* /*context*/, const ::pir_message::RequestData* /*request*/, ::pir_message::ResponseData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPIR(
      ::grpc::CallbackServerContext* /*context*/, const ::pir_message::RequestData* /*request*/, ::pir_message::ResponseData* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetDBInfo<WithCallbackMethod_GetPIR<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetDBInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDBInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetDBInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDBInfo(::grpc::ServerContext* /*context*/, const ::pir_message::DBInfoRequest* /*request*/, ::pir_message::DBInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPIR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPIR() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetPIR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPIR(::grpc::ServerContext* /*context*/, const ::pir_message::RequestData* /*request*/, ::pir_message::ResponseData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDBInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDBInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetDBInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDBInfo(::grpc::ServerContext* /*context*/, const ::pir_message::DBInfoRequest* /*request*/, ::pir_message::DBInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDBInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPIR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPIR() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetPIR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPIR(::grpc::ServerContext* /*context*/, const ::pir_message::RequestData* /*request*/, ::pir_message::ResponseData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPIR(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDBInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDBInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDBInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDBInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDBInfo(::grpc::ServerContext* /*context*/, const ::pir_message::DBInfoRequest* /*request*/, ::pir_message::DBInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDBInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPIR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPIR() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPIR(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPIR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPIR(::grpc::ServerContext* /*context*/, const ::pir_message::RequestData* /*request*/, ::pir_message::ResponseData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPIR(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDBInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDBInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pir_message::DBInfoRequest, ::pir_message::DBInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pir_message::DBInfoRequest, ::pir_message::DBInfo>* streamer) {
                       return this->StreamedGetDBInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDBInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDBInfo(::grpc::ServerContext* /*context*/, const ::pir_message::DBInfoRequest* /*request*/, ::pir_message::DBInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDBInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pir_message::DBInfoRequest,::pir_message::DBInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPIR : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPIR() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pir_message::RequestData, ::pir_message::ResponseData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pir_message::RequestData, ::pir_message::ResponseData>* streamer) {
                       return this->StreamedGetPIR(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPIR() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPIR(::grpc::ServerContext* /*context*/, const ::pir_message::RequestData* /*request*/, ::pir_message::ResponseData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPIR(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pir_message::RequestData,::pir_message::ResponseData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetDBInfo<WithStreamedUnaryMethod_GetPIR<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetDBInfo<WithStreamedUnaryMethod_GetPIR<Service > > StreamedService;
};

}  // namespace pir_message


#endif  // GRPC_pirmessage_2eproto__INCLUDED
